config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:show, :index]
  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news', as: 'tech_news'
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  get 'portfolios/angular', to: 'portfolios#angular'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Helio Duarte Portfolio") %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Helio Duarte Portfolio") %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "Helio Duarte Portfolio") %>
<% end %>

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p><%= copyright_generator %> </p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Hélio Duarte</h3>
    <nav class="nav nav-masthead">
      <%= nav_helper 'nav-link def_nav', 'span'%>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= copyright_generator%> </p>
  <%= source_helper("Blog")%>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">The Bootstrap Blog</h1>
    <p class="lead blog-description">An example blog template built with Bootstrap.</p>
    <span>
      <%= link_to 'New Blog', new_blog_path if logged_in?(:site_admin)%>
    </span>

    <div>
      <%= link_to "Topics", topics_path%>
    </div>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<%= nav_helper 'nav-link', 'span'%>
<%= login_helper 'nav-link'%>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>

  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p> <%= link_to topic.title, topic_path(topic.id) %> </p>
    <% end %>
  </div>

  <div class="sidebar-module">
    <h4>Personal Links</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/hbdf"><%= fa_icon "github"%></a></li>
    </ol>
  </div>
</div><!-- /.blog-sidebar -->

app/views/shared/_nav.html.erb
<div class="<%= location %>"> 
  <div> <%= link_to "Home", root_path %> </div> 
  <div> <%= link_to "About", about_path %> </div> 
  <div> <%= link_to "Contact", contact_path %> </div> 
  <div> <%= link_to "Blog", blogs_path %> </div> 
  <div> <%= link_to "Portfolio", portfolios_path %> </div> 
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <%= copyright_generator %>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My portfolio</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <%= link_to "Find out more about me", about_path, class: "btn btn-primary"%>
      <%= link_to "See my blog posts", blogs_path, class: "btn btn-secondary"%>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row"> 
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Contact</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li'%>
          <li><%= link_to login_helper %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <%= link_to "Helio Duarte", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>